### ISSUE TITLE
WARNING THIS WILL BREAK YOUR JAILBREAK

### ISSUE THREAD

**Issue by Outdatedm3m3s** [nqcshady/unc0ver-dark#1]
breaks cydia, only sileo works. Do not use unless you wanna have to restore root fs!

**Comment by Diatrus** [comment]
FUD

**Comment by jonatansuarez1208** [comment]
NO IT WILL FUCK YOUR JAILBREAK AND CYDIA APP, STAY AWAY FROM THIS DEVELOPER HE HAS NO IDEA WHAT HE IS DOING IT JUST FUCK MY JAILBREAK

**Comment by jonatansuarez1208** [comment]
NO IT WILL FUCK YOUR JAILBREAK AND CYDIA APP, STAY AWAY FROM THIS DEVELOPER HE HAS NO IDEA WHAT HE IS DOING IT JUST FUCK MY JAILBREAK

**Comment by jonatansuarez1208** [comment]
NO IT WILL FUCK YOUR JAILBREAK AND CYDIA APP, STAY AWAY FROM THIS DEVELOPER HE HAS NO IDEA WHAT HE IS DOING IT JUST FUCK MY JAILBREAK

**Comment by sckova** [comment]
LMAO now I want to use it twice as much. Thanks for the FUD and for the laugh.

**Comment by Diatrus** [comment]
These people didn’t read instructions lol. All either iOS 11 users or pirates who can’t get rid of Cydown.

**Comment by sckova** [comment]
Yeah kek
