### ISSUE TITLE
Sileo not working 

### ISSUE THREAD

**Issue by TUPACBOY** [nqcshady/unc0ver-dark#10]
Sileo cant install or uninstall or upgrade tweaks and when new repos are added they disappear after a force close

iPhone X on 12.1

**Comment by beqee** [comment]
For me its like i can install tweaks, but after its installed it says done. And does not respring my device. 

Iphone 8 12.1.1

**Comment by TUPACBOY** [comment]
Yea it will download it but nothing actually installs

**Comment by beqee** [comment]
I think someone has already reported this so they might already be looking in to it.

**Comment by aquilodev** [comment]
I am having this issue too.

**Comment by Diatrus** [comment]
Fixed in latest compat layer update.
