### ISSUE TITLE
Cydia refresh loops and Sileo won't add anything to the Queue

### ISSUE THREAD

**Issue by CodeyMoore** [nqcshady/unc0ver-dark#15]
Just rootfs restored and installed Cydia and Sileo.
I haven't been able to load/install anything, Cydia refresh loops and Sileo wont let me install/add anything to the queue.

**Device:**
 - iOS Version: 11.3.1
 - iOS Device: iPad mini 2
 - U0-Dark Version: 1.0 (latest)

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver-dark

**Logs**
I ssh'd into my iPad then ran "apt-get update" but got an error -

"-sh-4.4# apt-get update
dyld: Library not loaded: /usr/lib/liblzma.5.dylib
  Referenced from: /usr/lib/libapt-pkg.5.0.dylib
  Reason: Incompatible library version: libapt-pkg.5.0.dylib requires version 8.0.0 or later, but liblzma.5.dylib provides version 6.0.0
Abort trap: 6"

**Comment by coglucas** [comment]
Have you tried running a rootfs restore after the issue occurred? Your first sentence makes it seem like you only did it before running u0 dark, so just trying to clarify.

**Comment by Diatrus** [comment]
@Ultra03 @CodeyMoore I confirmed that APT is broken on iOS 11 for some weird reason on Discord with Codey. I need an iOS 11 device for tests, but until then I can't really do much...

**Comment by trungking** [comment]
I had the same problem

**Comment by Diatrus** [comment]
Been a long time but, here it is https://github.com/nqcshady/unc0ver-dark/releases/tag/1.2.4-snapshot-7bb42c9-v2
