### ISSUE TITLE
NO IT WILL FUCK YOUR JAILBREAK AND CYDIA APP, STAY AWAY

### ISSUE THREAD

**Issue by jonatansuarez1208** [nqcshady/unc0ver-dark#17]
NO IT WILL FUCK YOUR JAILBREAK AND CYDIA APP, STAY AWAY

**Comment by jonatansuarez1208** [comment]
NO IT WILL FUCK YOUR JAILBREAK AND CYDIA APP, STAY AWAY FROM THIS DEVELOPER HE HAS NO IDEA WHAT HE IS DOING IT JUST FUCK MY JAILBREAK

**Comment by jonatansuarez1208** [comment]
NO IT WILL FUCK YOUR JAILBREAK AND CYDIA APP, STAY AWAY FROM THIS DEVELOPER HE HAS NO IDEA WHAT HE IS DOING IT JUST FUCK MY JAILBREAK

**Comment by jonatansuarez1208** [comment]
NO IT WILL FUCK YOUR JAILBREAK AND CYDIA APP, STAY AWAY FROM THIS DEVELOPER DIATRUS HE HAS NO IDEA WHAT HE IS DOING IT JUST FUCK MY JAILBREAK

**Comment by sckova** [comment]
Dude are you okay

**Comment by jackiedorland** [comment]
As an active member of this jailbreaks discord server and someone who uses it themselves,

This is retarded. Get a life.

**Comment by xMilesManx** [comment]
Hey dude. Try to chill out. 

If you’re having the error failed to extract bootstrap, all you oh have to do is try again with airplane mode turned OFF
