### ISSUE TITLE
Sileo is laggy AF even on a 300mb network and other errors

### ISSUE THREAD

**Issue by ZeroDNA** [nqcshady/unc0ver-dark#18]
- iOS Version: 12.1.1
 - iOS Device: iPhone 7 (9,3)
 - unc0ver Version: 1.03

 - [x] this is a bug others will be able to reproduce
 - [X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

Sileo gets 404 error on every repo after update and it says its in que but it isnt and wont add it the que, and Sileo is laggy af on 300mb wireless or data on phone.

**Comment by Diatrus** [comment]
I need screenshots of errors please. Does Cydia work?

**Comment by Diatrus** [comment]
Settled in Discord as a Sileo related issue, and not an unc0ver dark issue.
Screenshot:
![image](https://user-images.githubusercontent.com/8144478/56685109-26e6bd80-669f-11e9-98a5-8e1b4e06e38b.png)
