### ISSUE TITLE
Failed to install Sileo

### ISSUE THREAD

**Issue by kyondev** [nqcshady/unc0ver-dark#24]
**Describe the bug**
Sileo does not install through uncover dark. There’s only a fatal error being displayed. More below.

**To Reproduce**
1. Enable “Install Sileo”
2. Click on 'Jailbreak or Re-Jailbreak'
4. See error “Error (Fatal) Errno 2”

**Screenshots**
No screenshots. 

**Device**
 - iOS Version: iOS 12.1.2
 - iOS Device: iPhone 6
 - unc0ver Version: 3.0.1
- unc0ver Dark Version: 1.0b1

 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**

Error message:

Error (Fatal)
Errno: 2
Test: aptInstall(@[sileoDeb])
Filename: JailbreakViewController.m
Line: 2199
Function: jailbreak
Description: Failed to install Sileo.

Logs: https://pastebin.com/F7UcC2va

**Comment by Diatrus** [comment]
Fixed in 1.1.1
