### ISSUE TITLE
Sileo Installer doens’t work

### ISSUE THREAD

**Issue by Yaya48** [nqcshady/unc0ver-dark#25]
Unc0ver Dark Error 9

Failed to install sileo 

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.1.1
 - iOS Device: 
 - unc0ver Version: 1.1.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Diatrus** [comment]
No information. Make sure you're on unc0ver dark 1.1.1
