### ISSUE TITLE
Sileo sources randomly dissapear.

### ISSUE THREAD

**Issue by Cvenos** [nqcshady/unc0ver-dark#32]
i go to install a tweak and then randomly all my sources are gone except fir chimera. I add them all bacj and then later the day they dissapear again.

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 
 - iOS Device: 
 - unc0ver Version: 

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Diatrus** [comment]
This is a Sileo issue, not a jailbreak issue.
