### ISSUE TITLE
Reload System Daemons working fine

### ISSUE THREAD

**Issue by HelloDefender12** [nqcshady/unc0ver-dark#33]
Reload system daemons is working fine for me iPhone 5s on unc0ver dark 1.1.5 but there is no Cydia.

**Comment by HelloDefender12** [comment]
Sorry for posting this here in issues.

**Comment by HelloDefender12** [comment]
Nice Work! Diatrus

**Comment by HelloDefender12** [comment]
Another problem when I press get in Sileo the button seems to be not working

**Comment by Diatrus** [comment]
Install cydia with sileo
