### ISSUE TITLE
Bug : Package install stuck on running 

### ISSUE THREAD

**Issue by HelloDefender12** [nqcshady/unc0ver-dark#34]
Dear Diatrus

When I press install on a package it just shows only running sometimes please fix...

May God Bless You

Hell0Defender12

**Comment by Diatrus** [comment]
Can you screenshot errors?

**Comment by HelloDefender12** [comment]
Okay

**Comment by HelloDefender12** [comment]
Wait

**Comment by HelloDefender12** [comment]
Here the link: https://imgur.com/a/DVR628B

**Comment by HelloDefender12** [comment]
Still lots of bugs XD

**Comment by Diatrus** [comment]
This is due to the repo/package, not Cydia.

**Comment by HelloDefender12** [comment]
It seems as though you have a bug in your program. Let me eat it.

**Comment by HelloDefender12** [comment]
Hmmm

**Comment by HelloDefender12** [comment]
👍 Thanks Diatrus 👍
