### ISSUE TITLE
Sileo not installing tweaks

### ISSUE THREAD

**Issue by nediaH** [nqcshady/unc0ver-dark#36]
Woke up this morning and no tweaks will install in Sileo. Everything was fine last night. I don’t have any of the forbidden tweaks installed that were mentioned in discord.

**Comment by Diatrus** [comment]
No info. Probably solvable by looking at common issues. Remove Ocean.

**Comment by nediaH** [comment]
I don’t have ocean installed

**Comment by nediaH** [comment]
Or any of the forbidden tweaks for that matter

**Comment by Diatrus** [comment]
Then post error codes. There’s an issue template for a reason. Or, if it is the classic no-error-code-but-won’t-install, you **do** have a Sileo tweak.

**Comment by nediaH** [comment]
Yeah there isnt any error codes. I guess I’ll just try to uninstall all of my tweaks until it works. To be fair Sileo was installing tweaks last night flawlessly, I installed Succesion and SnapBack and then went to bed, and now neither of them will uninstall. So 🤷‍♂️

**Comment by Diatrus** [comment]
Odd. This will be fixed when we add substitute but that won’t be for a while. However, I’m telling you that the only way that happens is if you have a Sileo tweak.

**Comment by nediaH** [comment]
If when you say “Sileo tweak” meaning a tweak that directly effects Sileo, I can’t recall ever installing something that would effect Sileo

**Comment by nediaH** [comment]
I fixed it. I just used my snapshot from right before I went to sleep and now I’m able to install tweaks again. Strange
