### ISSUE TITLE
Legacy uicache behavior triggered

### ISSUE THREAD

**Issue by HelloDefender12** [nqcshady/unc0ver-dark#37]
What is this Legacy uicache behavior triggered will this slow down my jailbroken device.?

How to fix this?

**Comment by coglucas** [comment]
This is caused by a tweak using the old `uicache` utility. This only slows down the installation of the tweak, not your device. The developer of the tweak will have to fix this.

**Comment by Diatrus1969** [comment]
ULTRA3 CUM MY PENIS!!!!
