### ISSUE TITLE
Sileo doesn't install anything.

### ISSUE THREAD

**Issue by m3rtngs** [nqcshady/unc0ver-dark#4]
I am using an iPhone 7 on iOS 12.1.1. I restored rootfs before using this fork of unc0ver and everything was working well. After installing around 10ish tweaks, Sileo refuses to install anything else. For example, I attempted to install PreferenceOrganizer 2 and when I press confirm, it downloads the tweak then goes to the install screen where nothing happens. It's just a blank log and when I try to see details it is also blank. All that I can do is press done and then after that nothing happens. I have checked to see whether it was just this tweak causing this and I tried installing themes and other tweaks but it doesn't work.

**Comment by Diatrus** [comment]
Please check our discord announcements for the list of tweaks that break sileo.

**Comment by m3rtngs** [comment]
Link?

Sent from my iPhone

On 14 Apr 2019, at 3:52 pm, Diatrus <notifications@github.com<mailto:notifications@github.com>> wrote:


Please check our discord announcements for the list of tweaks that break sileo.
