### ISSUE TITLE
Cydia crash

### ISSUE THREAD

**Issue by Cvenos** [nqcshady/unc0ver-dark#5]
After using the unc0ver dark application to to jailbreak and install Sileo, it breaks Cydia. I am unable to open it because it just instantly crashes. I was trying to get all my repos from Cydia to add them to Sileo but can't open Cydia. Hopefully you can fix this!

**Comment by Cvenos** [comment]
I was able to solve this issue with Diatrus over discord.

**Comment by zyan910** [comment]
Share the steps so that others can solve it too w/o opening another issue

**Comment by Diatrus** [comment]
@zyan910 he needed to remove Cydown.
