### ISSUE TITLE
Who those who have issues on 4K devices

### ISSUE THREAD

**Issue by HelloDefender12** [nqcshady/unc0ver-dark#52]
Those who have problems on 4K devices. Please  Use Unc0ver dark 1.1.5 its much stable on 4K devices 

Latest Versions of Unc0ver Dark Have problems and bugs.

**Comment by Randomblock1** [comment]
GitHub Issues is a place for bugs and feature requests, not general advice/common sense such as updating software to the latest version. Please only submit issues when you encounter an error or need help.
If you would like to submit feedback, please do so in the [Unc0ver Dark Discord](https://discord.gg/4pYwBCb).
Please close this issue. Thank you.
