### ISSUE TITLE
Unc0ver Dark conflicts with Unc0ver for AppDelegate URL

### ISSUE THREAD

**Issue by Randomblock1** [nqcshady/unc0ver-dark#53]
**Describe the bug**
When opening undecimus://jailbreak with both versions of Unc0ver installed (from Ignition), Safari throws an error and nothing opens.
side note: this was encountered while creating a shortcut that will automatically jailbreak for you

**To Reproduce**
1. Have both versions of Unc0ver installed
2. Go to undecimus://jailbreak via Safari (undecimus:// also fails)
3. See error

**Device (please complete the following information):**
 - iOS Version: 12.1.2
 - iOS Device: iPhone 6
 - unc0ver Version: Latest version

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**How to fix:**
Change [line 112 in AppDelegate.m](https://github.com/nqcshady/unc0ver-dark/blob/master/Undecimus/source/AppDelegate.m#L112) to something else, like undecimus-dark://jailbreak or unc0ver-dark://jailbreak. This should fix it, at least in theory.

**Comment by Cryptiiiic** [comment]
Fixed in [https://github.com/nqcshady/unc0ver-dark/commit/360fdb8490abc633648b4c8e9d5c20298a41794d](https://github.com/nqcshady/unc0ver-dark/commit/360fdb8490abc633648b4c8e9d5c20298a41794d)

IPA: [here](https://github.com/nqcshady/unc0ver-dark/releases/tag/1.2.4-snapshot-097073b-v1)
