### ISSUE TITLE
Jailbreak completes but will not respring the device and there's no cydia or sileo.

### ISSUE THREAD

**Issue by kid1carus** [nqcshady/unc0ver-dark#54]
Jailbreak runs as expected but when it finishes it does not respring the device so a manual restart has to be done.  
![IMG_0001](https://user-images.githubusercontent.com/45052773/58442874-4f0d7600-80bc-11e9-87f2-eb8da4f8e2b1.PNG)

Also, neither cydia or sileo have been installed on the device so i cant try the trick of installing a tweak to get the device to respring and correct itself.
![IMG_5DBE9B5B2231-1](https://user-images.githubusercontent.com/45052773/58442911-8d0a9a00-80bc-11e9-9c91-e91bdcdcbefd.jpeg)
![IMG_5DBE9B5B2231-2](https://user-images.githubusercontent.com/45052773/58442913-9136b780-80bc-11e9-979d-6d5bc9845a15.jpeg)

the bug is repeatable. its happened now 6 times in a row.

**Device (please complete the following information):**
 - iOS Version: 12.1
 - iOS Device: iPad Mini 2
 - unc0ver Version: 1.2.2

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by EthanHumphrey** [comment]
I also have this issue (minus the no Sileo/cydia). Every time I reboot and re-jailbreak I get to the prompt and press OK. After pressing OK it closes the app fully jailbroken but not resprung. I then have to go to the settings app and find a tweak preference sheet that has a respring option to fully reload my tweaks.

**Comment by jsassu20** [comment]
Upon first execution the app creates an image of your rootfs, then restarts. It should jailbreak after one or two more tries.

**Comment by xxccvip11** [comment]
good
