### ISSUE TITLE
Device reboots instead of respring

### ISSUE THREAD

**Issue by IamTheGoblins** [nqcshady/unc0ver-dark#60]
**Describe the bug**
Every day or two jailbreak won’t work as it’s supposed to and will reboot instead of respring, the previous version of the app had this issue as well, and it was easily fixed by resetting the caches in the settings. Now I have to restore rootfs before jailbreak works again.

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.1.3 Beta
 - iOS Device: iPhone X
 - unc0ver Version: 

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Cryptiiiic** [comment]
Please use the template provided, you straight up ignored it. Does this happen with reloaded systems daemons on as well as off?

Closing in around 7 days of no reply.

**Comment by Cryptiiiic** [comment]
Please use the template provided, you straight up ignored it. Does this happen with reloaded systems daemons on as well as off? @IamTheGoblins 

Closing in around 7 days of no reply.

**Comment by IamTheGoblins** [comment]
i used it as best as i could with the device im on, and for it being my
first time submitting a bug report, sorry for trying too help, you sure
taught me a lesson.

**Comment by Syndrrome** [comment]
@IamTheGoblins Post unc0ver diagnostics. Check Settings > Privacy > Analytics > Analytics Data for any SpringBoard, backboard, or panic-full crash logs and post them here if so.
