### ISSUE TITLE
#feature request

### ISSUE THREAD

**Issue by redgitid** [nqcshady/unc0ver-dark#62]
Add red accent with true black pls

**Comment by Syndrrome** [comment]
@tgbetauser Does Dark Meridian work for you? Closing this if no response because technically this is resolved.

**Comment by redgitid** [comment]
Have Dark meridian red accent?

**Comment by shny-scott** [comment]
yes, it has a red accent, it's the theme I currently use

**Comment by Syndrrome** [comment]
Yes, is this good enough for you?
![image](https://user-images.githubusercontent.com/53323134/62003782-fca70080-b0d0-11e9-8ab5-6c2ff22c8806.png)
![image](https://user-images.githubusercontent.com/53323134/62003785-0597d200-b0d1-11e9-914e-d8ca0b0c11e3.png)
@tgbetauser

**Comment by redgitid** [comment]
Thanks
