### ISSUE TITLE
iOS 12.1.3-12.2 Support

### ISSUE THREAD

**Issue by 10Meisterbaelle** [nqcshady/unc0ver-dark#64]
iOS 12.1.3-12.2 Support

**Comment by SarKaa** [comment]
And 12.3, like the original unc0ver

**Comment by 10Meisterbaelle** [comment]
Yes, but only 12.3 b1-b5

Watking01 <notifications@github.com> schrieb am Fr. 26. Juli 2019 um 16:21:

**Comment by Syndrrome** [comment]
It's getting worked on. No eta. Waiting patiently is your best bet. @neumaif02 @Watking01

**Comment by 10Meisterbaelle** [comment]
Why does this take so long?

Syndrome(Buddy Pine) <notifications@github.com> schrieb am Sa. 27. Juli
2019 um 09:15:

**Comment by Syndrrome** [comment]
@neumaif02 Stop acting entitled, you assume that it shouldn't take that long. How bout I just stop adding support because of you.

**Comment by 10Meisterbaelle** [comment]
Sorry😢. But why does this take so long?

Syndrome(Buddy Pine) <notifications@github.com> schrieb am Di. 30. Juli
2019 um 03:17:

**Comment by NoGos032850** [comment]
Any updates?
