### ISSUE TITLE
Sileo does let me install uninstall or upgrade any tweaks. The sources are also empty except for chariz and dynastic on ios 11.3. Just switched from regular unc0ver.

### ISSUE THREAD

**Issue by rb108** [nqcshady/unc0ver-dark#67]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.
Sileo does let me install uninstall or upgrade any tweaks. The sources are also empty except for chariz and dynastic on ios 11.3. Just switched from regular unc0ver.
**To Reproduce**
1. Jailbreak with unc0ver Dark
2. Open Sileo
3. Try to install anything
4. Sources are empty, nothing can be installed or uninstalled or upgraded

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 11.3
 - iOS Device: iPhone X
 - unc0ver Version: unc0ver dark 3.2.4

**Place an "x" between the brackets if true:**
 - [Unsure ] this is a bug others will be able to reproduce
 - [ x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x ] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Syndrrome** [comment]
@rb108 There is no 3.2.4 unc0ver dark. What exact version are you using.(Screenshot in app console). Can you ssh and run the command apt and screenshot the output.
