### ISSUE TITLE
[Requset] Bundle Core Utilities and Profile Directory with unc0ver dark

### ISSUE THREAD

**Issue by captinc** [nqcshady/unc0ver-dark#68]
Just requesting that Core Utilities and Profile Directory be bundled with unc0ver dark

**Comment by Syndrrome** [comment]
@Diatrus

**Comment by Diatrus** [comment]
Any specific reason you’d like this?

**Comment by Syndrrome** [comment]
@captinc ^

**Comment by captinc** [comment]
@Diatrus Mainly for unity between the 3 jailbreaks. I feel like it would be easier to have these command line tools already included. It would also pre-satisfy 2 more dependencies of some tweaks installed from .debs

**Comment by Diatrus** [comment]
@captinc That isn't a good enough reason imo. It wouldn't create unity, unc0ver stock doesn't bundle them afaik, and they aren't essential.

**Comment by captinc** [comment]
No problem, but just FYI unc0ver stock does bundle them @Diatrus
