### ISSUE TITLE
Automated Blob Saving (Aaron shut the other ideas down ;( )

### ISSUE THREAD

**Issue by debouncedgit** [nqcshady/unc0ver-dark#71]
### **Automated Blob Saving**

**Describe the feature you'd like**
Add a option in the settings that pulls our nonce and saves blobs automatically. Maybe make it manually, or automated during Jailbreaking Process..

**Additional context**
Despite there being things such as TSS-Saver, most people are too technologically illiterate and/or have the memory of no memory. We forget to save or blobs, or people don't know how to. This is an "Ease of Access" feature in which would enhance the usage of u0-dark.

**TAKEN INTO CONSIDERATION ^**

**Comment by 23Aaron** [comment]
Looked into the issue, unfortunately it's not really feasible.
