### ISSUE TITLE
Sileo does not display packages in repos and does not save repos on respring

### ISSUE THREAD

**Issue by DanielRoberts21** [nqcshady/unc0ver-dark#8]
**Describe the bug**
I used the install sileo feature but when I go to use it, none of the repositories work and I cannot add any without them being deleted again when I respring the device.

**To Reproduce**
1. Install Sileo using the switch on DarkUnc0ver
2. Open sileo
3. Look into repositories or try to add
4. Respring

**Screenshots**
![IMG_0490](https://user-images.githubusercontent.com/8289250/56157859-7bf84480-5fb8-11e9-9b3c-ffdf95263ceb.JPG)
![IMG_0491](https://user-images.githubusercontent.com/8289250/56157860-7bf84480-5fb8-11e9-8a03-ac9d28878646.JPG)
![IMG_0489](https://user-images.githubusercontent.com/8289250/56157861-7c90db00-5fb8-11e9-9cc7-5207e96f5296.JPG)

**Device (please complete the following information):**
 - iOS Version: 12.1.1b3
 - iOS Device: iPhone9,3
 - unc0ver Version: 

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Diatrus** [comment]
Check the #common-issues in our Discord server.
